services:
  db_service:
    platform: linux/amd64
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env.db.local
    volumes:
      - postgresql_data:/var/lib/postgresql/data/

  redis:
    platform: linux/amd64
    image: redis:alpine

  frontend:
    platform: linux/amd64
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5001
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    platform: linux/amd64
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env.api.local
    entrypoint: ["/app/entrypoint.sh"]
    depends_on:
      - db_service
      - redis

volumes:
  postgresql_data:
