services:
  db_service:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - ./ra_ui_backend/.env.db.local
    volumes:
      - postgresql_data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine

  frontend:
    build: ./ra_ui_frontend
    image: silvinwillemsen/choras-frontend:latest
    ports:
      - "5433:5433"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5001
    volumes:
      - ./ra_ui_frontend:/app
      - /app/node_modules

  backend:
    build: ./ra_ui_backend
    image: silvinwillemsen/choras-backend:latest
    ports:
      - "5001:5001"
    volumes:
      - ./ra_ui_backend:/app
    env_file:
      - ./ra_ui_backend/.env.api.local
    entrypoint: ["/app/entrypoint.sh"]
    depends_on:
      - db_service
      - redis

volumes:
  postgresql_data:
